image: gitpod/workspace-base

tasks:
  - name: ESP32-C3 Blink Setup
    init: |
      sudo apt-get update &&
      sudo apt-get install -y python3 python3-pip git wget flex bison gperf cmake ninja-build ccache libusb-1.0-0 &&
      git clone --recursive -b v4.4.4 https://github.com/espressif/esp-idf.git &&
      ./esp-idf/install.sh esp32c3 &&
      . ./esp-idf/export.sh &&
      mkdir -p main &&
      echo 'idf_component_register(SRCS "blink.c")' > main/CMakeLists.txt &&
      cat > main/blink.c << 'EOF'
      #include "driver/gpio.h"
      #include "freertos/FreeRTOS.h"
      #include "freertos/task.h"

      #define BLINK_GPIO 8

      void app_main() {
          gpio_reset_pin(BLINK_GPIO);
          gpio_set_direction(BLINK_GPIO, GPIO_MODE_OUTPUT);
          while(1) {
              gpio_set_level(BLINK_GPIO, 1);
              vTaskDelay(500 / portTICK_PERIOD_MS);
              gpio_set_level(BLINK_GPIO, 0);
              vTaskDelay(500 / portTICK_PERIOD_MS);
          }
      }
      EOF
    command: idf.py set-target esp32c3 && idf.py build
