image: gitpod/workspace-base

tasks:
  - name: ESP32-C3 Setup
    init: >
      sudo apt-get update &&
      # Устанавливаем Python3 и pip явно
      sudo apt-get install -y python3 python3-pip &&
      # Остальные зависимости
      sudo apt-get install -y git wget flex bison gperf cmake ninja-build ccache libusb-1.0-0 &&
      # Клонируем ESP-IDF с подмодулями
      git clone --recursive -b v4.4.4 https://github.com/espressif/esp-idf.git &&
      # Устанавливаем инструменты ESP-IDF
      ./esp-idf/install.sh esp32c3 &&
      # Настраиваем окружение
      . ./esp-idf/export.sh &&
      # Создаём проект Blink
      mkdir -p main &&
      echo 'idf_component_register(SRCS "blink.c")' > main/CMakeLists.txt &&
      printf '#include "driver/gpio.h"\n#include "freertos/FreeRTOS.h"\n#include "freertos/task.h"\n\n#define BLINK_GPIO 8\n\nvoid app_main() {\n    gpio_reset_pin(BLINK_GPIO);\n    gpio_set_direction(BLINK_GPIO, GPIO_MODE_OUTPUT);\n    while(1) {\n        gpio_set_level(BLINK_GPIO, 1);\n        vTaskDelay(500 / portTICK_PERIOD_MS);\n        gpio_set_level(BLINK_GPIO, 0);\n        vTaskDelay(500 / portTICK_PERIOD_MS);\n    }\n}' > main/blink.c
    command: idf.py set-target esp32c3 && idf.py build
