image: gitpod/workspace-base

tasks:
  - name: ESP32-C3 Blink Setup
    init: |
      # Устанавливаем зависимости
      sudo apt-get update &&
      sudo apt-get install -y python3 python3-pip git wget flex bison gperf cmake ninja-build ccache libusb-1.0-0 &&
      
      # Клонируем ESP-IDF
      git clone --recursive -b v4.4.4 https://github.com/espressif/esp-idf.git &&
      
      # Устанавливаем инструменты
      ./esp-idf/install.sh esp32c3 &&
      . ./esp-idf/export.sh &&
      
      # Создаем структуру проекта
      mkdir -p blink_project/main &&
      cd blink_project &&
      
      # CMakeLists для main компонента
      cat > main/CMakeLists.txt << 'EOF'
      idf_component_register(SRCS "blink.c"
                            INCLUDE_DIRS ".")
      EOF
      
      # Исходный код
      cat > main/blink.c << 'EOF'
      #include "driver/gpio.h"
      #include "freertos/FreeRTOS.h"
      #include "freertos/task.h"

      #define BLINK_GPIO 8

      void app_main() {
          gpio_reset_pin(BLINK_GPIO);
          gpio_set_direction(BLINK_GPIO, GPIO_MODE_OUTPUT);
          while(1) {
              gpio_set_level(BLINK_GPIO, 1);
              vTaskDelay(500 / portTICK_PERIOD_MS);
              gpio_set_level(BLINK_GPIO, 0);
              vTaskDelay(500 / portTICK_PERIOD_MS);
          }
      }
      EOF
    command: cd blink_project && idf.py set-target esp32c3 && idf.py build
