image: gitpod/workspace-base

tasks:
  - name: Setup ESP32-C3 Environment
    init: |
      # Установка зависимостей
      sudo apt-get update
      sudo apt-get install -y git wget flex bison gperf python3 cmake ninja-build ccache
      
      # Клонирование ESP-IDF
      git clone -b v5.1.1 --recursive https://github.com/espressif/esp-idf.git
      ./esp-idf/install.sh esp32c3
      . ./esp-idf/export.sh
      
      # Создание минимального проекта
      mkdir -p main
      echo 'idf_component_register(SRCS "blink.c" INCLUDE_DIRS "")' > main/CMakeLists.txt
      cat > main/blink.c << 'EOF'
#include "driver/gpio.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

void app_main() {
    gpio_reset_pin(8);
    gpio_set_direction(8, GPIO_MODE_OUTPUT);
    while(1) {
        gpio_set_level(8, 1);
        vTaskDelay(500);
        gpio_set_level(8, 0);
        vTaskDelay(500);
    }
}
EOF
    command: idf.py set-target esp32c3 && idf.py build
